spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking_management_db?useSSL=false
    username: root
    password: root

  #JPA Settings
  jpa.hibernate.ddl_auto: validate

pms:
  hourlyRate: {
    HANDICAPPED: 20,
    COMPACT: 20,
    LARGE: 40,
    MOTORBIKE: 10,
    ELECTRIC: 30
  }

##################################
#spring.datasource.url=jdbc:mysql://localhost:3306/parking_management_db?useSSL=false
#spring.datasource.username:root
#spring.datasource.password:root

#  jpa.hibernate.ddl_auto:create